name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  fl_chart: ^0.63.0
  excel: ^2.0.1
  permission_handler: ^11.3.0
  open_file: ^3.3.1
  universal_html: ^2.2.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15


dependency_overrides:
  fl_chart: ^0.63.0




flutter:
  uses-material-design: true
